# Reference: https://build-cpp.github.io/cmkr/cmake-toml
# to build:
# > cmake -B build
# > cmake --build build --config Release
[project]
name = "CSharpAPIProject"
languages = ["CXX", "C", "CSharp"]
cmake-after = """
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /MP")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /MP")
set(CMAKE_CSharp_FLAGS "${CMAKE_CSHARP_FLAGS} /langversion:latest /platform:x64")

# Disable exceptions
# string(REGEX REPLACE "/EHsc" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")

set(ASMJIT_STATIC ON CACHE BOOL "" FORCE)
set(DYNAMIC_LOADER ON CACHE BOOL "" FORCE) # OpenXR
set(BUILD_TOOLS OFF CACHE BOOL "" FORCE) # DirectXTK

if ("${CMAKE_BUILD_TYPE}" MATCHES "Release")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /MT")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /MT")

    # Statically compile runtime
    string(REGEX REPLACE "/MD" "/MT" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
    string(REGEX REPLACE "/MD" "/MT" CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
    string(REGEX REPLACE "/MD" "/MT" CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE}")
    string(REGEX REPLACE "/MD" "/MT" CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE}")
    
    message(NOTICE "Building in Release mode")
endif()

set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")

set(NUGET_PACKAGES_DIR "$ENV{NUGET_PACKAGES}")

# If NUGET_PACKAGES_DIR is not set, fall back to the default location
if(NOT NUGET_PACKAGES_DIR)
    if(WIN32)
        set(DEFAULT_NUGET_PATH "$ENV{USERPROFILE}/.nuget/packages")
    else()
        set(DEFAULT_NUGET_PATH "$ENV{HOME}/.nuget/packages")
    endif()
    set(NUGET_PACKAGES_DIR ${DEFAULT_NUGET_PATH})
endif()

# Set a bool if the generated reference assemblies exist in the build/bin folder
set(dll1 "${CMAKE_BINARY_DIR}/bin/REFramework.NET._System.dll")
set(dll2 "${CMAKE_BINARY_DIR}/bin/REFramework.NET.application.dll")
set(dll3 "${CMAKE_BINARY_DIR}/bin/REFramework.NET.viacore.dll")

# Initialize a variable to keep track of the existence of all files
set(REFRAMEWORK_REF_ASSEMBLIES_EXIST TRUE)

# Check if each DLL exists
foreach(dll IN ITEMS ${dll1} ${dll2} ${dll3})
  if(NOT EXISTS ${dll})
    set(REFRAMEWORK_REF_ASSEMBLIES_EXIST FALSE)
    break() # Exit the loop as soon as one file is not found
  endif()
endforeach()


# Use the result
if(REFRAMEWORK_REF_ASSEMBLIES_EXIST)
  message(STATUS "All specified DLLs exist.")
else()
  message(STATUS "One or more specified DLLs do not exist.")
endif()
"""

[conditions]
build-csharp-test = "REFRAMEWORK_REF_ASSEMBLIES_EXIST"

[template.CSharpSharedTarget]
type = "shared"

[template.CSharpSharedTarget.properties]
RUNTIME_OUTPUT_DIRECTORY_RELEASE = "${CMAKE_BINARY_DIR}/bin/"
RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO = "${CMAKE_BINARY_DIR}/bin"
LIBRARY_OUTPUT_DIRECTORY_RELEASE = "${CMAKE_BINARY_DIR}/lib"
DOTNET_SDK = "Microsoft.NET.Sdk"
DOTNET_TARGET_FRAMEWORK = "net8.0-windows"
VS_CONFIGURATION_TYPE = "ClassLibrary"

[target.REFCSharpCompiler]
type = "CSharpSharedTarget"
sources = ["Compiler/**.cs"]

# Not using .properties here because it overrides the template properties for whatever reason
cmake-after = """
set_target_properties(REFCSharpCompiler PROPERTIES VS_PACKAGE_REFERENCES "Microsoft.CodeAnalysis_4.9.2")
"""

[target.csharp-api]
type = "shared"
include-directories = ["../include/"]
sources = ["REFrameworkNET/**.cpp", "REFrameworkNET/**.c"]
headers = ["REFrameworkNET/**.hpp", "REFrameworkNET/**.h"]
compile-features = ["cxx_std_20"]
compile-options = ["/EHa", "/MD", "/doc"]
link-libraries = [
    "REFCSharpCompiler"
]
cmake-after = """
# Copy nuget packages to the output directory
add_custom_command(
   TARGET csharp-api POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_directory ${NUGET_PACKAGES_DIR}/microsoft.codeanalysis.csharp/4.9.2/lib/net7.0 ${CMAKE_BINARY_DIR}/bin//
    COMMENT "Copying nuget packages"
)
add_custom_command(
   TARGET csharp-api POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_directory ${NUGET_PACKAGES_DIR}/microsoft.codeanalysis.common/4.9.2/lib/net7.0 ${CMAKE_BINARY_DIR}/bin//
    COMMENT "Copying nuget packages"
)
set(REFRAMEWORK_DOT_NET_ASSEMBLY_DIR "${CMAKE_BINARY_DIR}/bin")
set(REFRAMEWORK_DOT_NET_ASSEMBLY_PATH "${CMAKE_BINARY_DIR}/bin/REFramework.NET.dll")

set_target_properties(csharp-api PROPERTIES
VS_DOTNET_REFERENCE_REFCSharpCompiler
"${REFRAMEWORK_DOT_NET_ASSEMBLY_DIR}/REFCSharpCompiler.dll"
)

set_target_properties(csharp-api PROPERTIES VS_PACKAGE_REFERENCES "REFCSharpCompiler")
"""

[target.csharp-api.properties]
OUTPUT_NAME = "REFramework.NET"
RUNTIME_OUTPUT_DIRECTORY_RELEASE = "${CMAKE_BINARY_DIR}/bin/"
RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO = "${CMAKE_BINARY_DIR}/bin/"
LIBRARY_OUTPUT_DIRECTORY_RELEASE = "${CMAKE_BINARY_DIR}/lib/"
COMMON_LANGUAGE_RUNTIME = "netcore"
DOTNET_TARGET_FRAMEWORK = "net8.0-windows"
# DOTNET_TARGET_FRAMEWORK_VERSION = "net8.0"
VS_GLOBAL_EnableManagedPackageReferenceSupport = "true"
# VS_PACKAGE_REFERENCES = "Microsoft.CodeAnalysis_4.9.2"

[target.AssemblyGenerator]
type = "CSharpSharedTarget"
sources = ["AssemblyGenerator/**.cs"]
link-libraries = [
    "csharp-api",
    "REFCSharpCompiler"
]
cmake-after = """
set_target_properties(AssemblyGenerator PROPERTIES
VS_DOTNET_REFERENCE_REFramework.NET
"${REFRAMEWORK_DOT_NET_ASSEMBLY_PATH}"
)
"""

[target.CSharpAPITest]
condition = "build-csharp-test"
type = "CSharpSharedTarget"
sources = ["test/Test/**.cs"]
link-libraries = [
    "csharp-api"
]

cmake-after = """
set_target_properties(CSharpAPITest PROPERTIES
VS_DOTNET_REFERENCE_REFramework.NET
"${REFRAMEWORK_DOT_NET_ASSEMBLY_PATH}"
)

set_target_properties(CSharpAPITest PROPERTIES
VS_DOTNET_REFERENCE_REFramework.NET._System
"${REFRAMEWORK_DOT_NET_ASSEMBLY_DIR}/REFramework.NET._System.dll"
)

set_target_properties(CSharpAPITest PROPERTIES VS_PACKAGE_REFERENCES "REFramework.NET._System")

set_target_properties(CSharpAPITest PROPERTIES
VS_DOTNET_REFERENCE_REFramework.NET.viacore
"${REFRAMEWORK_DOT_NET_ASSEMBLY_DIR}/REFramework.NET.viacore.dll"
)

set_target_properties(CSharpAPITest PROPERTIES VS_PACKAGE_REFERENCES "REFramework.NET.viacore")

set_target_properties(CSharpAPITest PROPERTIES
VS_DOTNET_REFERENCE_REFramework.NET.application
"${REFRAMEWORK_DOT_NET_ASSEMBLY_DIR}/REFramework.NET.application.dll"
)

set_target_properties(CSharpAPITest PROPERTIES VS_PACKAGE_REFERENCES "REFramework.NET.application")

"""